AdvancedViewProject/AdvancedViewProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('user/', include('user.urls')),
]

AdvancedViewProject/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('item_list/', views.item_list, name='item_list'),
    path('item_detail/<int:id>/', views.item_detail, name='item_detail'),
    path('to_google/', views.to_google, name='to_google'),
    path('one_item/', views.one_item, name='one_item'),
]

AdvancedViewProject/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('user_list/', views.user_list, name='user_list'),
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('info/', views.info, name='info'),
]

AdvancedViewProject/store/models.py
from django.db import models


class Items(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()

    class Meta:
        db_table = 'items'

    def __str__(self):
        return self.name

AdvancedViewProject/user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.FileField(upload_to='user/', blank=True)

    def __str__(self):
        return self.user.username

AdvancedViewProject/user/forms.py
from django import forms
from django.contrib.auth.models import User
from user.models import Profile


class UserForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    
    
    class Meta:
        model = User
        fields = ('username','email','password')


class ProfileForm(forms.ModelForm):
    website = forms.URLField(label='ホームページ')
    picture = forms.FileField(label='写真')

    class Meta:
        model = Profile
        fields = ('website', 'picture')


class LoginForm(forms.Form):
    username = forms.CharField(label='ユーザー名', max_length=150)
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード確認', widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが一致しません')

AdvancedViewProject/store/views.py
from django.shortcuts import render, redirect

from .models import Items


def item_list(request):
    items = Items.objects.all()
    return render(request, 'store/item_list.html', context={'items':items})


def item_detail(request, id):
    item = Items.objects.filter(pk=id).first()
    if item is None:
        return redirect('store:item_list')
    return render(request, 'store/item_detail.html', context={'item':item})


def to_google(request):
    return redirect('https://www.google.com/')


def one_item(request):
    return redirect('store:item_detail', id=1)

AdvancedViewProject/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from user.forms import UserForm, ProfileForm, LoginForm


def user_list(request):
    return render(request, 'user/user_list.html')

def index(request):
    return render(request, 'user/index.html')

def register(request):
    user_form = UserForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None, request.FILES or None)
    if user_form.is_valid() and profile_form.is_valid():
        user = user_form.save()
        user.set_password(user.password)
        user.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
    return render(request, 'user/register.html', context={'user_form':user_form, 'profile_form':profile_form})


def user_login(request):
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid():
        username = login_form.cleaned_data.get('username')
        password = login_form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('user:index')
            else:
                return HttpResponse('アカウントがアクティブではありません')
        else:
            return HttpResponse('ユーザーが存在しません')
    return render(request, 'user/login.html', context={'login_form':login_form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('user:index')


@login_required
def info(request):
    return HttpResponse('ログインしています')

AdvancedViewProject/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>AdvancedViewSample</title>
  </head>
  <body>
      <div class="container">
        <nav>
          <a href="{% url 'user:index' %}">ホーム</a>
          <a href="{% url 'admin:index' %}">管理画面</a>
          {% if user.is_authenticated %}
          <a href="{% url 'user:user_logout' %}">ログアウト</a>
          {% else %}
          <a href="{% url 'user:register' %}">登録画面</a>
          <a href="{% url 'user:user_login' %}">ログイン</a>
          {% endif %}
          <a href="{% url 'user:info' %}">インフォメーション</a>
        </nav>
          <h4>これはBase.htmlです</h4>
          <div class="container">
              {% block content %}
              {% endblock content %}
          </diV>
        </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

AdvancedViewProject/templates/store/item_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ item.name }}:{{ item.price }}円です</h1>

{% endblock content %}

AdvancedViewProject/templates/store/item_list.html
{% extends 'base.html' %}

{% block content %}
<table>
    <tr>
        <th>名前</th>
        <th>値段</th>
    </tr>
    {% for item in items %}
    <tr>
        <td><a href="{% url 'store:item_detail' id=item.id %}">{{ item.name }}</a></td>
        <td>{{ item.price}}円</td>
    </tr>
    {% endfor %}
{% endblock content %}

AdvancedViewProject/templates/user/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Login Sample</h1>



{% endblock content %}

AdvancedViewProject/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
<h1>ログイン画面</h1>
<form method="POST">
    {% csrf_token %}
    {{ login_form.as_p }}
    <input type="submit" value="ログイン">
</form>
{% endblock content %}

AdvancedViewProject/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
<h1>登録画面</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="登録">
</form>
{% endblock content %}

AdvancedViewProject/templates/user/user_list.html
{% extends 'base.html' %}

{% block content %}
<h1>ユーザーリスト</h1>
<a href="{% url 'store:item_list' %}">アイテムリスト</a>


{% endblock content %}